version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"