name: Deploy to Preview Channel

on:
  pull_request:
#    branches: [ !dependabot/** ]

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the Build
        run: exit 1
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - if: ${{ failure() }}
        run: |
            gh issue comment ${{ github.event.number }} -F body="**Deployment to Preview Channel Failed!**

            This pull request could not be deployed to the preview channel. Because of this, a tmate session has spawned!"
     
