name: Deploy to Preview Channel

on:
  pull_request:
#    branches: [ !dependabot/** ]

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the Build
        run: exit 1
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
