name: LGTM Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check for LGTM comment
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const comments = await github.rest.issues.listComments({
              issue_number: issue_number,
              owner: owner,
              repo: repo
            });

            for (const comment of comments.data) {
              if (comment.body.includes('LGTM')) {
                console.log('LGTM comment found!');
                return;
              }
            }

            throw new Error('No LGTM comment found!');
