name: Check Syntax

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y tidy
          npm install -g stylelint
          npm install -g jsonlint

      - name: Check modified files
        run: |
          git diff --name-only origin/${{ github.base_ref }}..${{ github.head_ref }} > modified_files.txt
          if grep -qE '\.(html|css|onc)$' modified_files.txt; then
            echo "HTML, CSS, or ONC files have been modified."
            exit 1
          else
            echo "No HTML, CSS, or ONC files have been modified."
          fi

      - name: Check HTML syntax
        run: |
          for file in $(grep -E '\.html$' modified_files.txt); do
            tidy -q -e $file
          done

      - name: Check CSS syntax
        run: |
          for file in $(grep -E '\.css$' modified_files.txt); do
            stylelint $file
          done

      - name: Check ONC syntax
        run: |
          for file in $(grep -E '\.onc$' modified_files.txt); do
            jsonlint $file
          done

      - name: Create review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEW_COMMENTS=""
          for file in $(grep -E '\.(html|css|onc)$' modified_files.txt); do
            if ! tidy -q -e $file || ! stylelint $file || ! jsonlint $file; then
              REVIEW_COMMENTS+="\n- $file has syntax errors."
            fi
          done
          if [ -z "$REVIEW_COMMENTS" ]; then
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
              -d '{
                "body": "All files follow correct syntax. Good job!",
                "event": "APPROVE"
              }'
          else
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
              -d "{
                \"body\": \"The following files have syntax errors: $REVIEW_COMMENTS\",
                \"event\": \"REQUEST_CHANGES\"
              }"
          fi
