name: Check Syntax

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y tidy
          npm install -g stylelint
          npm install -g jsonlint

      - name: Get modified files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
            | jq -r '.[] | select(.status != "removed") | .filename' > modified_files.txt
          DELETED_FILES=$(curl \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
            | jq -r '.[] | select(.status == "removed") | .filename')
          if [ -n "$DELETED_FILES" ]; then
            echo "Noticed deleted diff" > deleted_files.txt
          fi

      - name: Check HTML syntax
        run: |
          for file in $(grep -E '\.html$' modified_files.txt); do
            tidy -q -e $file || echo "$file: $(tidy -q -e $file)" >> html_errors.txt
          done

      - name: Check CSS syntax
        run: |
          for file in $(grep -E '\.css$' modified_files.txt); do
            stylelint $file || echo "$file: $(stylelint $file)" >> css_errors.txt
          done

      - name: Check ONC syntax
        run: |
          for file in $(grep -E '\.onc$' modified_files.txt); do
            jsonlint $file || echo "$file: $(jsonlint $file)" >> onc_errors.txt
          done

      - name: Create review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEW_COMMENTS=""
          for file in $(grep -E '\.(html|css|onc)$' modified_files.txt); do
            if [ -f html_errors.txt ] && grep -q "$file" html_errors.txt; then
              REVIEW_COMMENTS+="\n- $file has HTML syntax errors: $(grep "$file" html_errors.txt)"
            fi
            if [ -f css_errors.txt ] && grep -q "$file" css_errors.txt; then
              REVIEW_COMMENTS+="\n- $file has CSS syntax errors: $(grep "$file" css_errors.txt)"
            fi
            if [ -f onc_errors.txt ] && grep -q "$file" onc_errors.txt; then
              REVIEW_COMMENTS+="\n- $file has ONC syntax errors: $(grep "$file" onc_errors.txt)"
            fi
          done
          if [ -n "$REVIEW_COMMENTS" ]; then
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
              -d "{
                \"body\": \"The following files have syntax errors: $REVIEW_COMMENTS\",
                \"event\": \"REQUEST_CHANGES\"
              }"
          elif [ -f deleted_files.txt ]; then
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              -d '{
                "body": "Noticed deleted diff"
              }'
          else
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
              -d '{
                "body": "All files follow correct syntax. Good job!",
                "event": "APPROVE"
              }'
          fi
